'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const views={swara:{title:'Criterion weighting',sub:'Turn expert judgments into a clear set of criterion weights.',tag:'CSF–SWARA',action:'Calculate weights',intro:'CSF–SWARA combines circular spherical fuzzy expert assessments with stepwise weight assessment. The output is a normalized weight for each criterion.'},cocoso:{title:'Alternative ranking',sub:'Compare alternatives through optimistic and pessimistic scenarios.',tag:'CSF–CoCoSo',action:'Calculate ranking',intro:'CSF–CoCoSo integrates weighted fuzzy assessments into a combined compromise score. Supply your criterion weights and optional benefit or cost directions.'}};
const content=window.CSF_CONTENT&&typeof window.CSF_CONTENT==='object'?window.CSF_CONTENT:{};
function applyText(selector,value){const el=$(selector);if(el&&typeof value==='string')el.textContent=value}
function sectionMarkup(items){return (Array.isArray(items)?items:[]).filter(x=>x&&x.enabled!==false).map(x=>'<article class="card custom-section"><h3 dir="auto">'+escapeHTML(x.title||'')+'</h3><p dir="auto">'+escapeHTML(x.body||'')+'</p></article>').join('')}
if(typeof content.pageTitle==='string')document.title=content.pageTitle;
for(const [key,selector]of Object.entries({fuzzySetName:'#fuzzy-set-name',developerCredit:'#developer-credit',affiliation:'#header-affiliation',authorName:'.sidebar footer strong',footerCredit:'.main-footer>span:first-child'}))applyText(selector,content[key]);
applyText('.sidebar footer>span:not(.version)',content.affiliation);
const labelSelectors={workspace:'.nav-label',eyebrow:'.page-heading .eyebrow',setup:'.section-heading h2',workbook:'.field-heading label',template:'#template',example:'#example',parameters:'.setup-inner h3',help:'#help',helpTitle:'.dialog-head h2',emptyTitle:'.empty-result h2',emptyDescription:'.empty-result p',privacyTitle:'.sidebar-note strong',privacyDescription:'.sidebar-note p'};
for(const [key,selector]of Object.entries(labelSelectors))applyText(selector,content.labels?.[key]);
for(const m of ['swara','cocoso']){for(const key of Object.keys(views[m]))if(typeof content.methods?.[m]?.[key]==='string')views[m][key]=content.methods[m][key];const b=$('[data-method="'+m+'"]');b.lastElementChild.innerHTML=escapeHTML(views[m].tag)+'<small>'+escapeHTML(views[m].title)+'</small>';}
const sections=sectionMarkup(content.sections);$('#custom-sections').innerHTML=sections;$('#custom-sections').hidden=!sections;
const blankResult=$('#result-content').innerHTML;
let method='swara',state={swara:{sheets:null,name:'',demo:false,result:null},cocoso:{sheets:null,name:'',demo:false,result:null}},revision=0;
function feedback(text,error=false){$('#feedback').textContent=text;$('#feedback').classList.toggle('error',error)}
function clearResults(){state[method].result=null;$('#result-content').innerHTML=blankResult;$('#method-description').textContent=views[method].intro;revision++}
function selectMethod(m){if(!views[m])throw new Error('Unknown method');method=m;revision++;let v=views[m];$$('[data-method]').forEach(b=>{b.classList.toggle('active',b.dataset.method===m);b.setAttribute('aria-pressed',b.dataset.method===m)});$('#page-title').innerHTML=escapeHTML(v.title)+'<span class="title-dot">.</span>';$('#page-subtitle').textContent=v.sub;$('#method-tag').textContent=v.tag;$('#run').textContent=v.action;$('#run').disabled=!state[m].sheets;$('#lambda-control').hidden=m!=='cocoso';$('#file-label').textContent=state[m].name||'Choose an Excel workbook';$('#workbook').value='';if(state[m].result)renderResults(state[m].result);else{$('#result-content').innerHTML=blankResult;$('#method-description').textContent=v.intro}feedback(state[m].sheets?'Workbook ready. Review the parameters and calculate.':'Choose a workbook or load the example to begin.');}
function loadExample(){clearResults();state[method]={sheets:CSF.example(method),name:views[method].tag+' · synthetic example',demo:true,result:null};$('#file-label').textContent=state[method].name;$('#run').disabled=false;feedback('Synthetic example loaded. These are demonstration data.');}
function fromWorkbook(wb){if(wb.SheetNames.length>50)throw Error('Use at most 50 sheets.');let total=0;return Object.fromEntries(wb.SheetNames.map(name=>{let sh=wb.Sheets[name];if(sh['!ref']){let r=XLSX.utils.decode_range(sh['!ref']);total+=(r.e.r-r.s.r+1)*(r.e.c-r.s.c+1);if(total>100000)throw Error('Use at most 100,000 workbook cells.')}let aoa=XLSX.utils.sheet_to_json(sh,{header:1,defval:null,blankrows:false});if(!aoa.length)return[name,[]];let heads=aoa[0].map(x=>String(x??'').trim());let used=heads.map((x,i)=>i).filter(i=>heads[i]||aoa.slice(1).some(r=>r[i]!==null&&r[i]!==undefined&&r[i]!==''));let h=used.map(i=>heads[i]);if(h.some(x=>!x)||new Set(h).size!==h.length)throw Error(name+': column headers must be non-empty and unique.');return[name,aoa.slice(1).filter(r=>used.some(i=>r[i]!==null&&r[i]!==undefined&&r[i]!=='')).map(r=>Object.fromEntries(used.map(i=>[heads[i],r[i]??null])))]}))}
function checkArchiveSize(buffer){let b=new Uint8Array(buffer),v=new DataView(buffer);if(b[0]!==80||b[1]!==75)return;let entries=0,total=0;for(let i=0;i+46<b.length;i++){if(v.getUint32(i,true)===0x02014b50){entries++;total+=v.getUint32(i+24,true);if(entries>2000||total>60*1024*1024)throw Error('Workbook expands beyond the 60 MB limit.');i+=45+v.getUint16(i+28,true)+v.getUint16(i+30,true)+v.getUint16(i+32,true)}}}
async function uploadFile(file){if(!file)return;clearResults();const selected=method,token=revision;state[selected]={sheets:null,name:'',demo:false,result:null};$('#run').disabled=true;$('#file-label').textContent='Reading workbook…';feedback('Reading workbook on this device…');try{if(!/\.(xlsx|xls)$/i.test(file.name)||!file.size||file.size>10*1024*1024)throw Error('Choose a non-empty .xlsx or .xls file up to 10 MB.');let buffer=await file.arrayBuffer();checkArchiveSize(buffer);let wb=XLSX.read(buffer,{type:'array',cellFormula:false,cellHTML:false,cellStyles:false}),sheets=fromWorkbook(wb);let hash=crypto.subtle?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer))).map(x=>x.toString(16).padStart(2,'0')).join(''):null;if(selected!==method||token!==revision)return;state[selected]={sheets,name:file.name,demo:false,result:null,hash};$('#file-label').textContent=file.name;$('#run').disabled=false;feedback('Workbook loaded. '+wb.SheetNames.length+' sheets · ready to validate and calculate.')}catch(e){if(selected!==method||token!==revision)return;$('#file-label').textContent='Choose an Excel workbook';feedback(e.message,true)}}
async function calculate(){const s=state[method];if(!s.sheets)throw Error('Choose a workbook first.');const selected=method,token=revision;$('#run').disabled=true;feedback('Validating workbook and calculating…');await new Promise(r=>setTimeout(r,30));try{let result=CSF.calculate(s.sheets,selected,Number($('#attitude').value),$('#radius').value,Number($('#lambda').value));if(selected!==method||token!==revision)return;result.metadata={software:'CSF Research',version:CSF.version,method:'Port of author equations from csf_mobile/core.py',module:selected,timestamp_utc:new Date().toISOString(),input_sha256:s.hash||null,input_filename:s.name,parameters:result.params,synthetic_demo:s.demo,diagnostics:{scenario_triples_outside_unit_sphere:result.diagnostics}};result.tables.Run_Metadata=Object.entries(result.metadata).map(([Field,Value])=>({Field,Value:typeof Value==='object'?JSON.stringify(Value):String(Value)}));s.result=result;renderResults(result);feedback('Analysis complete. Results are ready to export.');return{method:selected,rows:result.rows,diagnostics:result.diagnostics}}catch(e){if(selected===method&&token===revision){s.result=null;feedback(e.message,true)}throw e}finally{if(selected===method&&token===revision)$('#run').disabled=!s.sheets}}
function format(v){return typeof v==='number'?v.toLocaleString('en-US',{maximumFractionDigits:6}):escapeHTML(v)}
function table(rows,columns=Object.keys(rows[0]||{})){return '<div class="table-scroll"><table><thead><tr>'+columns.map(c=>'<th scope="col">'+escapeHTML(c.replaceAll('_',' '))+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+columns.map(c=>'<td>'+format(r[c])+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function renderResults(r){const is=r.module==='swara',key=is?'Criterion':'Alternative',value=is?'Final_SWARA_Weight':'Final_Crisp_Score',max=Math.max(...r.rows.map(x=>x[value])),s=state[r.module],total=r.rows.length;$('#result-content').innerHTML='<div class="metrics"><div class="card metric"><label>'+ (is?'Criteria':'Alternatives')+'</label><strong>'+total+'</strong></div><div class="card metric"><label>Expert judgments</label><strong>'+r.experts.length+' <span style="font-size:12px;font-weight:400">experts</span></strong></div><div class="card metric"><label>'+(is?'Highest weight':'Leading alternative')+'</label><strong class="accent">'+(is?(r.rows[0][value]*100).toFixed(1)+'%':escapeHTML(r.rows[0][key]))+'</strong></div></div><div class="card result-card"><div class="result-head"><div><h2>'+(is?'Criterion weight distribution':'Alternative ranking')+'</h2><p>'+(is?'Normalized weights · sum = 1.000':'Final compromise score · higher is better')+'</p></div><span class="badge">'+(s.demo?'SYNTHETIC EXAMPLE':'WORKBOOK RESULTS')+'</span></div><div class="bars">'+r.rows.map(x=>'<div class="bar-row"><span class="bar-label">'+escapeHTML(x[key])+'</span><div class="bar-track"><div class="bar-fill" style="width:'+Math.max(0,x[value]/max*100)+'%"></div></div><span class="bar-number">'+(is?(x[value]*100).toFixed(2)+'%':x[value].toFixed(4))+'</span></div>').join('')+'</div></div><div class="card result-card"><div class="result-head"><div><h2>Results & calculation trail</h2><p>Full precision is preserved in the Excel export.</p></div><button id="export" class="outline">Export Excel</button></div>'+table(r.rows,is?['Rank','Criterion','Score','Final_SWARA_Weight']:['Rank','Alternative','K_Optimistic','K_Pessimistic','Final_Crisp_Score'])+(r.diagnostics?'<div class="warning">'+r.diagnostics+' optimistic or pessimistic scenario centers exceed the unit sphere under the original equations. Review the method notes before interpreting these rankings.</div>':'')+'<details><summary>Inspect calculation steps</summary>'+Object.entries(r.tables).filter(([name])=>!['CSF_Scale','Run_Metadata','Parameters'].includes(name)).map(([name,rows])=>'<details><summary>'+escapeHTML(name.replaceAll('_',' '))+'</summary>'+table(rows)+'</details>').join('')+'</details><p class="meta-note">p = '+r.params.p.toFixed(2)+(is?'':' · λ = '+r.params.lambda.toFixed(2))+' · radius: '+r.params.radius_policy+' · '+(s.demo?'Demonstration data':'User workbook')+'</p><button id="record" class="text-button" style="margin-top:12px">Download reproducibility record</button></div>';$('#export').onclick=()=>exportResult();$('#record').onclick=()=>download(new Blob([JSON.stringify(r.metadata,null,2)],{type:'application/json'}),r.module+'_run.json');}
function workbook(tables){let wb=XLSX.utils.book_new(),used=new Set();Object.entries(tables).forEach(([name,rows])=>{let n=name.slice(0,31),i=1;while(used.has(n))n=name.slice(0,27)+'_'+i++;used.add(n);let sh=XLSX.utils.json_to_sheet(rows);sh['!cols']=Object.keys(rows[0]||{}).map(k=>({wch:Math.min(40,Math.max(16,k.length+2))}));XLSX.utils.book_append_sheet(wb,sh,n)});return new Blob([XLSX.write(wb,{type:'array',bookType:'xlsx',compression:true})],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
const downloads=new Map();function download(blob,name){const url=URL.createObjectURL(blob);downloads.set(url,name);let a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>{URL.revokeObjectURL(url);downloads.delete(url)},300000)}
window.csfDownloadName=url=>downloads.get(url)||'csf_results.xlsx';
function exportResult(){let r=state[method].result;if(!r)return;download(workbook(r.tables),method+'_results.xlsx')}
function showHelp(){$('#help-content').innerHTML='<p>CSF Research supports two independent methods for circular spherical fuzzy decision analysis. Calculations run on your device; workbooks are not uploaded to a research server.</p><h3>1 · CSF–SWARA</h3><p>Use <code>SWARA_Evaluations</code> with <code>Expert</code>, <code>Criterion</code> and <code>Term</code>. Enter each expert–criterion pair exactly once. Optional <code>R</code> is between 0 and 1; optional <code>S</code> is nonnegative. When S is blank, the original score function supplies comparative importance.</p><h3>2 · CSF–CoCoSo</h3><p>Use one decision matrix sheet per expert. The first column is <code>Alternative</code>, followed by one column per criterion. Long format with Alternative, Criterion and Value is also supported. Include <code>Criteria_Weights</code> with Criterion and Weight. All weights must be positive. An optional <code>Criteria_Types</code> sheet accepts Benefit or Cost.</p><h3>Expert weights</h3><p>An optional <code>Expert_Info</code> sheet contains Expert and either Weight or WeightTerm. Without this sheet, experts have equal weights. Every expert must be listed exactly once when it is supplied.</p><h3>Linguistic scale</h3>'+table(CSF.scaleRows())+'<h3>Method notes</h3><p>The author’s equations are preserved. SWARA uses each sorted criterion’s own score as S when S is absent. CoCoSo averages the optimistic and pessimistic K values equally. The scenario transformation clips components independently; some scenario centers can exceed the unit sphere. Such cases are reported, rather than silently changing the research method. A zero scenario count does not certify every intermediate fuzzy operation.</p><h3>Files and privacy</h3><p>Templates contain synthetic data. Inputs stay in memory on this device; closing or refreshing the page clears them. Export results before leaving. Imports are limited to 10 MB, 50 sheets and 100,000 cells. SWARA supports up to 50 experts and 250 criteria; CoCoSo supports up to 20,000 ratings.</p><p>Developed by Dr. Saeed Alinejad · Shiraz University, Iran.</p>';$('#help-content').innerHTML+=sectionMarkup(content.helpSections);$('#help-dialog').showModal()}
$$('[data-method]').forEach(b=>b.onclick=()=>selectMethod(b.dataset.method));$('.brand').onclick=e=>{e.preventDefault();selectMethod('swara')};$('#example').onclick=loadExample;$('#template').onclick=()=>download(workbook(CSF.example(method)),method+'_input_template.xlsx');$('#run').onclick=()=>calculate().catch(()=>{});$('#workbook').onchange=e=>uploadFile(e.target.files[0]);$('#help').onclick=showHelp;$('#close-help').onclick=()=>$('#help-dialog').close();$('#help-dialog').onclick=e=>{if(e.target===$('#help-dialog')){const b=e.target.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)e.target.close()}};
['attitude','lambda','radius'].forEach(id=>$('#'+id).addEventListener('input',()=>{$('#p-value').textContent=Number($('#attitude').value).toFixed(2);$('#lambda-value').textContent=Number($('#lambda').value).toFixed(2);Object.values(state).forEach(s=>s.result=null);clearResults();feedback(state[method].sheets?'Parameters changed. Calculate again to update the results.':'Choose a workbook or load the example to begin.')}));
const zone=$('#dropzone');['dragenter','dragover'].forEach(t=>zone.addEventListener(t,e=>{e.preventDefault();zone.classList.add('drag')}));['dragleave','drop'].forEach(t=>zone.addEventListener(t,e=>{e.preventDefault();zone.classList.remove('drag')}));zone.addEventListener('drop',e=>uploadFile(e.dataTransfer.files[0]));
if(document.modelContext?.registerTool){const abort=new AbortController();const tools=[{name:'read_csf_results',description:'Read the current CSF analysis results without changing them.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({method,result:state[method].result?.rows||null})},{name:'calculate_loaded_csf_workbook',description:'Validate and calculate the loaded workbook using the current visible method and parameters. Requires a workbook or example to be loaded.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:input=>{if(input&&Object.keys(input).length)throw Error('This tool accepts no parameters.');return calculate()}}];for(const t of tools){try{Promise.resolve(document.modelContext.registerTool(t,{signal:abort.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>abort.abort(),{once:true})}
selectMethod('swara');

