/* CSF Research 2.0. Numerical port of the author's csf_mobile/core.py.
 * Equations deliberately preserved; validation follows service.py.
 * The mathematical limitations described in METHOD_NOTES.md still apply. */
(function(root){'use strict';
const scale={AI:[.9,.1,.1],VHI:[.8,.2,.2],HI:[.7,.3,.3],MI:[.6,.4,.4],EI:[.5,.5,.5],MLI:[.4,.6,.4],LI:[.3,.7,.3],VLI:[.2,.8,.2],AL:[.1,.9,.1]};
const description=['Absolutely Important','Very High Important','High Important','Minimum Important','Equal Importance','Medium/Low Important','Low Important','Very Low Important','Absolutely Low'];
const A={expert:['expert','decision_maker','dm','name'],criterion:['criterion','criteria','factor','attribute','column','c'],value:['value','term','evaluation','assessment','score','rating'],weight:['weight','w','criterion_weight','criteria_weight'],type:['type','criterion_type','criteria_type','benefit_cost','direction'],alternative:['alternative','alternatives','option','options','challenge','row','item','case','a'],radius:['r','radius'],relative:['s','sj','relative_importance','relativeimportance','comparative_importance'],expertise:['weightterm','term','linguistic','expertise','level']};
const names={info:['expert_info','experts','expert_weights','decision_makers','dm_weights'],weights:['criteria_weights','criterion_weights','weights','swara_weights'],types:['criteria_types','criterion_types','types','benefit_cost','criteria_info'],swara:['swara_evaluations','swara','criteria_evaluations','criterion_evaluations']};
const sum=a=>a.reduce((s,v)=>s+v,0),prod=a=>a.reduce((s,v)=>s*v,1),unique=a=>[...new Set(a)],clip=x=>Math.max(0,Math.min(1,x)),blank=x=>x===null||x===undefined||String(x).trim()==='',norm=x=>String(x??'').trim().toLowerCase().replace(/ /g,'_'),text=x=>String(x??'').trim().replace(/[۰-۹٠-٩٫٬]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.includes(c)?'۰۱۲۳۴۵۶۷۸۹'.indexOf(c):'٠١٢٣٤٥٦٧٨٩'.includes(c)?'٠١٢٣٤٥٦٧٨٩'.indexOf(c):'.');
function fail(m){throw new Error(m)}
function number(v,label,high=Infinity){if(blank(v))fail(label+' must be numeric.');let n=Number(text(v));if(!Number.isFinite(n)||n<0||n>high)fail(label+' is outside its permitted range.');return n}
function id(v,label){if(blank(v))fail(label+' contains a blank identifier.');return String(v).trim()}
function column(rows,aliases){return Object.keys(rows[0]||{}).find(k=>aliases.includes(norm(k)))}
function term(v){let s=text(v);if(!s)fail('Empty linguistic rating.');let n=Number(s);if(Number.isFinite(n)){if(!Number.isInteger(n)||n<1||n>9)fail('Numeric linguistic ratings must be integers from 1 to 9.');return Object.keys(scale)[9-n]}
let key=s.toUpperCase().replace(/[\s_-]/g,'');if(scale[key])return key;
const aliases={ABSOLUTELYIMPORTANT:'AI',ABSOLUTELYHIGH:'AI',AH:'AI',VERYHIGHIMPORTANT:'VHI',VERYHIGH:'VHI',VH:'VHI',HIGHIMPORTANT:'HI',HIGH:'HI',H:'HI',MINIMUMIMPORTANT:'MI',MODERATEIMPORTANT:'MI',MEDIUMHIGH:'MI',MH:'MI',EQUALIMPORTANCE:'EI',EQUAL:'EI',AVERAGE:'EI',AE:'EI',LOWIMPORTANT:'MLI',MEDIUMLOW:'MLI',ML:'MLI',LOW:'LI',L:'LI',VERYLOWIMPORTANT:'VLI',VERYLOW:'VLI',VL:'VLI',ABSOLUTELYLOW:'AL'};if(aliases[key])return aliases[key];let p=s.replace(/ /g,'');if(/بسیارزیاد|کاملازیاد|کاملاًزیاد|قطعا/.test(p))return'AI';if(p.includes('خیلیزیاد'))return'VHI';if(/زیاد|بالا/.test(p))return'HI';if(p.includes('متوسط')&&!/کم|پایین/.test(p))return'EI';if(p.includes('خیلیکم'))return'VLI';if(/کاملاکم|کاملاًکم/.test(p))return'AL';if(/کم|پایین/.test(p))return'LI';fail('Invalid linguistic rating: '+s)}
const score=(x,p)=>.25*(x[0]-x[1]-x[2]+Math.SQRT2+x[3]*(2*p-1));
function aggregate(values,weights,policy){let total=sum(weights),w=weights.map(x=>x/total),T=Math.sqrt(Math.max(0,1-prod(values.map((v,i)=>(1-v[0]**2)**w[i])))),I=prod(values.map((v,i)=>v[1]**w[i])),F=prod(values.map((v,i)=>v[2]**w[i])),explicit=values.some(v=>v[3]>0),geo=explicit?prod(values.map((v,i)=>(v[3]<=0?1e-12:v[3])**w[i])):0,disp=values.length>1?Math.max(...values.map(v=>Math.sqrt((v[0]-T)**2+(v[1]-I)**2+(v[2]-F)**2))):0,r=policy==='max'?Math.max(geo,disp):explicit?Math.min(geo,disp):disp;return[T,I,F,r].map(clip)}
function add(a,b,policy){return[Math.sqrt(Math.max(0,a[0]**2+b[0]**2-a[0]**2*b[0]**2)),a[1]*b[1],a[2]*b[2],policy==='max'?Math.max(a[3],b[3]):Math.min(a[3],b[3])].map(clip)}
function scalar(x,w){return[Math.sqrt(Math.max(0,1-(1-x[0]**2)**w)),x[1]**w,x[2]**w,x[3]>0?x[3]**w:0].map(clip)}
function power(x,w){return[x[0]**w,x[1]**w,Math.sqrt(Math.max(0,1-(1-x[2]**2)**w)),x[3]>0?x[3]**w:0].map(clip)}
function addMany(v,policy){return v.reduce((a,b)=>add(a,b,policy),[0,1,1,policy==='max'?0:1])}
function scenarios(x){let[T,I,F,r]=x;return[[T+r,I-r,F-r,r].map(clip),[T-r,I+r,F+r,r].map(clip)]}
function auxiliary(sheets,aliases){let found=Object.entries(sheets).filter(([n])=>aliases.includes(norm(n)));if(found.length>1)fail('Multiple sheets supplied for the same auxiliary input.');return found[0]?.[1]||null}
function exactRows(rows,key,expected,label){let ids=rows.map(r=>id(r[key],label));if(unique(ids).length!==ids.length||ids.length!==expected.length||expected.some(x=>!ids.includes(x)))fail(label+' must contain exactly one row for every identifier.');return new Map(rows.map(r=>[id(r[key],label),r]))}
function expertWeights(experts,info){if(!info)return experts.map(Expert=>({Expert,Weight_Source:'Equal',Term_or_Value:'Equal',Raw_Expert_Value:1,Expert_Weight:1/experts.length}));let ec=column(info,A.expert),wc=column(info,A.weight),tc=column(info,A.expertise);if(!ec)fail('Expert_Info needs an Expert column.');let lookup=exactRows(info,ec,experts,'Expert_Info');let rows=experts.map(Expert=>{let r=lookup.get(Expert),raw,source,value;if(wc&&!blank(r[wc])){raw=number(r[wc],'Expert weight');if(raw<=0)fail('Expert weights must be positive.');source='Numeric weight';value=raw}else if(tc&&!blank(r[tc])){value=term(r[tc]);let[T,I,F]=scale[value],h=Math.max(0,1-T*T-I*I-F*F);raw=T+h*(T/Math.max(1e-12,1-h));source='CSF expertise term'}else fail('Each expert requires a weight or expertise term.');return{Expert,Weight_Source:source,Term_or_Value:value,Raw_Expert_Value:raw}});let total=sum(rows.map(r=>r.Raw_Expert_Value));return rows.map(r=>({...r,Expert_Weight:r.Raw_Expert_Value/total}))}
function dense(rows,key){let v=unique(rows.map(r=>r[key])).sort((a,b)=>b-a);return rows.map(r=>({...r,Rank:v.indexOf(r[key])+1}))}
function swara(sheets,p,policy){let rows=auxiliary(sheets,names.swara)||Object.values(sheets).find(r=>column(r,A.expert)&&column(r,A.criterion)&&column(r,A.value));if(!rows?.length)fail('Add SWARA_Evaluations with Expert, Criterion and Term columns.');let ec=column(rows,A.expert),cc=column(rows,A.criterion),vc=column(rows,A.value),rc=column(rows,A.radius),sc=column(rows,A.relative);if(!ec||!cc||!vc)fail('SWARA requires Expert, Criterion and Term columns.');let entries=rows.map(r=>({e:id(r[ec],'Expert'),c:id(r[cc],'Criterion'),t:term(r[vc]),r:rc&&!blank(r[rc])?number(r[rc],'Radius',1):0,s:sc&&!blank(r[sc])?number(r[sc],'S'):null}));let experts=unique(entries.map(r=>r.e)),criteria=unique(entries.map(r=>r.c));if(experts.length>50||criteria.length>250)fail('Use at most 50 experts and 250 criteria.');if(entries.length!==experts.length*criteria.length||unique(entries.map(r=>JSON.stringify([r.e,r.c]))).length!==entries.length)fail('Provide exactly one rating for every expert–criterion pair.');let ew=expertWeights(experts,auxiliary(sheets,names.info)),w=new Map(ew.map(r=>[r.Expert,r.Expert_Weight])),terms=[],aggregated=[];
let weights=criteria.map(Criterion=>{let sub=entries.filter(r=>r.c===Criterion),values=sub.map(r=>[...scale[r.t],r.r]),ws=sub.map(r=>w.get(r.e)),agg=aggregate(values,ws,policy),Score=score(agg,p),Accuracy=sum(agg.slice(0,3)),s=sub.filter(r=>r.s!==null),rel=s.length?sum(s.map(r=>r.s*w.get(r.e)))/sum(s.map(r=>w.get(r.e))):Score;
sub.forEach((r,i)=>terms.push({Expert:r.e,Criterion,Input_Term:r.t,Expert_Weight:ws[i],T:values[i][0],I:values[i][1],F:values[i][2],r:r.r}));let base={Criterion,T:agg[0],I:agg[1],F:agg[2],r:agg[3],Score,Accuracy};aggregated.push(base);return{...base,Relative_Importance_Source:s.length?'Numeric S':'Score function',Relative_Importance_S:rel}}).sort((a,b)=>b.Score-a.Score||b.Accuracy-a.Accuracy);
let q=1;weights=weights.map((r,i)=>{let S_used=i?Math.max(0,r.Relative_Importance_S):0,K_j=1+S_used;q/=K_j;return{...r,Order:i+1,S_used,K_j,q_j:q}});let total=sum(weights.map(r=>r.q_j));weights=dense(weights.map(r=>({...r,Final_SWARA_Weight:r.q_j/total})),'Final_SWARA_Weight');return{module:'swara',rows:weights,experts:ew,criteria,diagnostics:0,tables:{Final_SWARA_Weights:weights,Aggregated_CSF:aggregated,Expert_Weights:ew,Input_Terms:terms}}}
function matrix(rows,label){if(!rows.length)fail(label+': empty decision matrix.');let ac=column(rows,A.alternative),cc=column(rows,A.criterion),vc=column(rows,A.value),alts,criteria,values;if(ac&&cc&&vc){alts=unique(rows.map(r=>id(r[ac],'Alternative')));criteria=unique(rows.map(r=>id(r[cc],'Criterion')));let lookup=new Map(rows.map(r=>[JSON.stringify([id(r[ac],'Alternative'),id(r[cc],'Criterion')]),term(r[vc])]));if(lookup.size!==rows.length||rows.length!==alts.length*criteria.length)fail(label+': provide every alternative–criterion pair exactly once.');values=alts.map(a=>criteria.map(c=>lookup.get(JSON.stringify([a,c]))))}else{let keys=Object.keys(rows[0]);if(keys.length<2)fail(label+': add an Alternative column and criteria.');alts=rows.map(r=>id(r[keys[0]],'Alternative'));if(unique(alts).length!==alts.length)fail(label+': duplicate alternatives.');criteria=keys.slice(1).map(c=>id(c,'Criterion'));values=rows.map(r=>keys.slice(1).map(k=>term(r[k])))}return{alts,criteria,values}}
function isAux(name){let n=norm(name);return[...names.info,...names.weights,...names.types].includes(n)||['scale','readme','instruction','guide','result','output','parameter','template'].some(k=>n.includes(k))}
function criterionInput(sheets,criteria){let wr=auxiliary(sheets,names.weights);if(!wr?.length)fail('Add Criteria_Weights with Criterion and Weight columns.');let cc=column(wr,[...A.criterion,'name']),wc=column(wr,A.weight);if(!cc||!wc)fail('Criteria_Weights requires Criterion and Weight columns.');let wl=exactRows(wr,cc,criteria,'Criteria_Weights'),weights=criteria.map(c=>number(wl.get(c)[wc],'Criterion weight'));if(weights.some(w=>w<=0))fail('Criterion weights must be positive.');let total=sum(weights);weights=weights.map(w=>w/total);let types=criteria.map(()=> 'Benefit'),tr=auxiliary(sheets,names.types);if(tr){cc=column(tr,[...A.criterion,'name']);let tc=column(tr,A.type);if(!cc||!tc)fail('Criteria_Types requires Criterion and Type.');let tl=exactRows(tr,cc,criteria,'Criteria_Types');types=criteria.map(c=>{let t=norm(tl.get(c)[tc]);if(!['benefit','cost'].includes(t))fail('Criterion types must be Benefit or Cost.');return t==='cost'?'Cost':'Benefit'})}return{weights,types}}
function positive(x){let m=Math.min(...x);return m<=1e-9?x.map(v=>v-m+1e-9):x}
function kValues(S,P,lam){let s=positive(S),p=positive(P),den=sum(s)+sum(p),mins=Math.min(...s),minp=Math.min(...p),maxs=Math.max(...s),maxp=Math.max(...p);return s.map((v,i)=>{let a=(v+p[i])/den,b=v/mins+p[i]/minp,c=(lam*v+(1-lam)*p[i])/(lam*maxs+(1-lam)*maxp);return[a,b,c,Math.cbrt(Math.max(a*b*c,0))+(a+b+c)/3]})}
function cocoso(sheets,p,policy,lam){let experts=Object.keys(sheets).filter(n=>!isAux(n));if(!experts.length)fail('No expert decision matrix found.');let m=experts.map(n=>matrix(sheets[n],n)),{alts,criteria}=m[0];if(m.some(x=>JSON.stringify([x.alts,x.criteria])!==JSON.stringify([alts,criteria])))fail('All expert sheets must use identical alternative and criterion order.');if(alts.length*criteria.length*experts.length>20000)fail('Use at most 20,000 expert–alternative–criterion ratings.');let ew=expertWeights(experts,auxiliary(sheets,names.info)),{weights,types}=criterionInput(sheets,criteria),ag=alts.map((a,i)=>criteria.map((c,j)=>{let v=aggregate(m.map(x=>[...scale[x.values[i][j]],0]),ew.map(e=>e.Expert_Weight),policy);return types[j]==='Cost'?[v[2],v[1],v[0],v[3]]:v})),o=ag.map(row=>row.map(v=>scenarios(v)[0])),pe=ag.map(row=>row.map(v=>scenarios(v)[1]));let diagnostics=[...o.flat(),...pe.flat()].filter(v=>sum(v.slice(0,3).map(x=>x*x))>1+1e-12).length;
let run=mat=>{let S=mat.map(row=>score(addMany(row.map((v,j)=>scalar(v,weights[j])),policy),p)),P=mat.map(row=>score(addMany(row.map((v,j)=>power(v,weights[j])),policy),p));return{S,P,K:kValues(S,P,lam)}};let op=run(o),ps=run(pe);let rows=alts.map((Alternative,i)=>({Alternative,S_Optimistic:op.S[i],P_Optimistic:op.P[i],Kia_Optimistic:op.K[i][0],Kib_Optimistic:op.K[i][1],Kic_Optimistic:op.K[i][2],K_Optimistic:op.K[i][3],S_Pessimistic:ps.S[i],P_Pessimistic:ps.P[i],Kia_Pessimistic:ps.K[i][0],Kib_Pessimistic:ps.K[i][1],Kic_Pessimistic:ps.K[i][2],K_Pessimistic:ps.K[i][3],Final_Crisp_Score:.5*(op.K[i][3]+ps.K[i][3])}));rows=dense(rows,'Final_Crisp_Score').sort((a,b)=>a.Rank-b.Rank||(a.Alternative<b.Alternative?-1:a.Alternative>b.Alternative?1:0));let tables={Final_CoCoSo_Ranking:rows,Criteria_Weights:criteria.map((Criterion,j)=>({Criterion,Weight:weights[j],Weight_Source:'Criteria_Weights'})),Criteria_Types:criteria.map((Criterion,j)=>({Criterion,Type:types[j]})),Expert_Weights:ew};let matrixRows=mat=>alts.map((Alternative,i)=>Object.fromEntries([['Alternative',Alternative],...criteria.map((c,j)=>[c,mat[i][j]])]));['aggregated_T','aggregated_I','aggregated_F','radius_r'].forEach((key,k)=>tables[key]=matrixRows(ag.map(row=>row.map(v=>v[k]))));tables.optimistic_score_matrix=matrixRows(o.map(row=>row.map(v=>score(v,p))));tables.pessimistic_score_matrix=matrixRows(pe.map(row=>row.map(v=>score(v,p))));experts.forEach((n,i)=>tables[('Terms_'+n).slice(0,31)]=matrixRows(m[i].values));tables.Skipped_Sheets=Object.keys(sheets).filter(isAux).map(Skipped_sheets=>({Skipped_sheets}));return{module:'cocoso',rows,experts:ew,criteria,diagnostics,tables}}
function scaleRows(){return Object.entries(scale).map(([Symbol,v],i)=>({Symbol,Description:description[i],T:v[0],I:v[1],F:v[2]}))}
function example(module){let info=[{Expert:'Expert_1',WeightTerm:'AI'},{Expert:'Expert_2',WeightTerm:'VHI'}];if(module==='swara')return{SWARA_Evaluations:['AI','VHI','HI','MI','VHI','HI','MI','EI'].map((Term,i)=>({Expert:i<4?'Expert_1':'Expert_2',Criterion:'C'+(i%4+1),Term,R:0,S:null})),Expert_Info:info,CSF_Scale:scaleRows(),ReadMe:[{Note:'Synthetic example. Required columns: Expert, Criterion, Term. Optional R and S. Blank S uses the score function.'}]};return{Expert_1:[{Alternative:'A1',C1:'AI',C2:'HI',C3:'VHI'},{Alternative:'A2',C1:'VHI',C2:'MI',C3:'HI'},{Alternative:'A3',C1:'HI',C2:'EI',C3:'MI'}],Expert_2:[{Alternative:'A1',C1:'VHI',C2:'HI',C3:'AI'},{Alternative:'A2',C1:'HI',C2:'EI',C3:'HI'},{Alternative:'A3',C1:'HI',C2:'MI',C3:'EI'}],Criteria_Weights:[{Criterion:'C1',Weight:.4},{Criterion:'C2',Weight:.35},{Criterion:'C3',Weight:.25}],Criteria_Types:[{Criterion:'C1',Type:'Benefit'},{Criterion:'C2',Type:'Benefit'},{Criterion:'C3',Type:'Cost'}],Expert_Info:info,CSF_Scale:scaleRows(),ReadMe:[{Note:'Synthetic example. One expert per sheet; Criteria_Weights required. Criteria_Types optional.'}]}}
function calculate(sheets,module,p=.5,policy='max',lam=.5){if(!['swara','cocoso'].includes(module)||!['max','min'].includes(policy))fail('Unknown method or radius policy.');p=number(p,'p',1);lam=number(lam,'Lambda',1);if(!sheets||typeof sheets!=='object'||Object.keys(sheets).length>50)fail('Use at most 50 sheets.');let cells=Object.values(sheets).reduce((a,rows)=>a+rows.length*Object.keys(rows[0]||{}).length,0);if(cells>100000)fail('Use at most 100,000 input cells.');let result=module==='swara'?swara(sheets,p,policy):cocoso(sheets,p,policy,lam);result.tables.CSF_Scale=scaleRows();result.params={p,radius_policy:policy,...(module==='cocoso'?{lambda:lam}:{})};result.tables.Parameters=[result.params];for(let r of result.rows)for(let v of Object.values(r))if(typeof v==='number'&&!Number.isFinite(v))fail('Non-finite calculation result. Please review the input and parameters.');return result}
root.CSF={calculate,example,scaleRows,term,score,aggregate,scenarios,version:'2.0.0'};if(typeof module!=='undefined'&&module.exports)module.exports=root.CSF;
})(typeof globalThis!=='undefined'?globalThis:this);
